name: Update test site

on:
  push:
    branches:
      - main
    paths:
      - '.github/workflows/**'
      - 'source/frontend/**'
jobs:
  deploy:
    name: Build & deploy for test site
    uses: ./.github/workflows/buildAndDeployActions.yml
    secrets:
      VALIST_DEPLOY_PRIVATE_KEY: ${{ secrets.VALIST_DEPLOY_PRIVATE_KEY }}
      VALIST_DEPLOY_PROJECT_NAME: sendcryptotest
